### ISSUE TITLE
Catkin_make Error

### ISSUE THREAD

**Issue by DengMark** [ethz-ait/duo3d_ros#2]
Hello, when I try to build the duo3d_ros package, it said that :

driverDUOstereo.cpp:325:95: error: ‘EnumerateResolutions’ was not declared in this scope
 
When I return back to the source code, It is not declared in fact, but I have not found it in any other file.

so how to solve it ?

**Comment by saimouli** [comment]
@DengMark I am facing the same issue. Can you share you approach to solving it.
